server:
  port: 2333

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:change-me-strong-password}
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    # 짧은 효과음 위주의 사용을 고려한 기본 버퍼값
    bufferDurationMs: 400
    frameBufferDurationMs: 5000

metrics:
  prometheus:
    enabled: false
